version: '3'
services:
  redis:
    image: dockerfile:latest
    ports:
      - "6379"
    volumes:
      - /tmp/redis:/tmp/redis
    restart: always 
  kafka:
    image: dockerfile:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER=http://127.0.0.1:8080/produce
      - KAFKA_TOPIC=test
    volumes:
      - /tmp/kafka:/tmp/kafka
    depends_on:
      - redis
